# Generated by Django 5.2.6 on 2025-09-24 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPaid', models.BooleanField(default=False, help_text='Indicates whether the client has paid.')),
                ('isBlocked', models.BooleanField(default=False, help_text='Indicates whether the client is blocked from service.')),
                ('disconnect_connection', models.BooleanField(default=False, help_text="Indicates whether the client's connection has been disconnected.")),
                ('price', models.DecimalField(decimal_places=2, help_text='The price or fee associated with the client.', max_digits=10)),
                ('client_name', models.CharField(help_text='The name of the client.', max_length=255)),
                ('client_url', models.URLField(help_text='A URL related to the client.')),
                ('slug', models.SlugField(help_text='A URL-friendly slug for the client.', unique=True)),
                ('client_review', models.IntegerField(default=0, help_text='A review score from 0 to 10.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('order_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the order was placed.')),
                ('delivery_date', models.DateTimeField(blank=True, help_text='The date and time of the order delivery.', null=True)),
                ('project_description', models.TextField(blank=True, help_text='A detailed description of the project.', null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['client_name'],
            },
        ),
    ]
